export const DATA = [
  {
    id: "e1",
    title: "Two Sums",
    amount: 1,
    date: new Date(2020, 7, 14),
    cat: "Queue",
  },
  {
    id: "e2",
    title: "Swap Nodes in Pairs",
    amount: 2,
    date: new Date(2021, 2, 12),
    cat: "Stackk",
  },
  {
    id: "e3",
    title: "Plaindrome",
    amount: 3114,
    date: new Date(2021, 5, 28),
    cat: "Queue",
  },
  {
    id: "e4",
    title: "Add Two Numbers",
    amount: 450,
    date: new Date(2021, 7, 12),
    cat: "Queue",
  },
  {
    id: "e5",
    title: "Median of Two Sorted Arrays",
    amount: 552,
    date: new Date(2022, 8, 12),
    cat: "Queue",
  },
  {
    id: "e6",
    title: "Zigzag Conversion",
    amount: 968,
    date: new Date(2022, 9, 12),
    cat: "Stackk",
  },
  {
    id: "e7",
    title: "Integer to Roman",
    amount: 2536,
    date: new Date(2019, 12, 12),
    cat: "Queue",
  },
  {
    id: "e8",
    title: "Letter Combinations of a Phone Number",
    amount: 7854,
    date: new Date(2021, 11, 12),
    cat: "Stackk",
  },
  {
    id: "e9",
    title: " Combination Sum II",
    amount: 125,
    date: new Date(2020, 1, 12),
    cat: "Queue",
  },
  {
    id: "e10",
    title: "Search Insert Position",
    amount: 935,
    date: new Date(2020, 7, 12),
    cat: "Stackk",
  },
  {
    id: "e11",
    title: "Substring with Concatenation of All Words",
    amount: 8562,
    date: new Date(2020, 3, 12),
    cat: "Queue",
  },
  {
    id: "e12",
    title: "Reverse Nodes in k-Group",
    amount: 1248,
    date: new Date(2020, 9, 12),
    cat: "Queue",
  },
  {
    id: "e13",
    title: " Letter Combinations of a Phone Number",
    amount: 256,
    date: new Date(2019, 4, 12),
    cat: "Stackk",
  },
  {
    id: "e14",
    title: " Longest Common Prefix",
    amount: 78541,
    date: new Date(2019, 2, 12),
    cat: "Queue",
  },
  {
    id: "e15",
    title: "Roman to Integer",
    amount: 156,
    date: new Date(2019, 8, 12),
    cat: "Stackk",
  },
  {
    id: "e16",
    title: "Container With Most Water",
    amount: 5423,
    date: new Date(2019, 12, 12),
    cat: "Queue",
  },
];
